#
# Configuring Active Record:
# <https://guides.rubyonrails.org/configuring.html#configuring-active-record>
#
# Database Connection Control Functions
# <https://www.postgresql.org/docs/current/libpq-connect.html>
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: rideshare
  prepared_statements: true # enabled by default
  advisory_locks: true # enabled by default
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  # Optional (PostgreSQL):
  # checkout_timeout, read_timeout

test:
  <<: *default

development:
  <<: *default
  database: rideshare_development
  variables:
    # https://www.postgresql.org/docs/current/runtime-config-client.html
    statement_timeout: 20000 # (in seconds, consider lowering to 5s for OLTP)
    idle_in_transaction_session_timeout: 300000 # milliseconds
    # Consider setting all these params:
    # idle_timeout
    # lock_timeout
    # idle_session_timeout
