# https://circleci.com/developer/orbs/orb/circleci/ruby
version: 2.1

# https://circleci.com/developer/orbs/orb/circleci/ruby
orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - ruby/install-deps

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.2.2
      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: rideshare_test
          POSTGRES_PASSWORD: postgres
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      RAILS_ENV: test
      PGSLICE_URL: "postgres://postgres:postgres@localhost:5432/rideshare_test"
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Test Database setup
          command: sh db/setup_test_database.sh
      - run:
          name: Database schema load
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Partition conversion
          command: sh bin/partition_conversion.sh
      - run:
          name: run tests
          command: bin/rails test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
